<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title'=> 'Il Signore degli Anelli',
                'publication_year'=> 1954,
                'plot' => ' Frodo intraprende un viaggio per distruggere l\'Unico Anello e salvare la Terra di Mezzo.',
                'price' => 24.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Harry Potter e la Pietra Filosofale',
                'publication_year' => 1997,
                'plot' => 'Un giovane mago scopre il proprio destino nella scuola di Hogwarts.',
                'price' => 18.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Dune',
                'publication_year' => 1965,
                'plot' => 'Paul Atreides affronta intrighi politici e guerre sul pianeta desertico Arrakis.',
                'price' => 22.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => '1984',
                'publication_year' => 1949,
                'plot' => 'Un uomo vive sotto il controllo di un regime totalitario che sorveglia ogni aspetto della vita.',
                'price' => 14.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Nome della Rosa',
                'publication_year' => 1980,
                'plot' => "Un frate francescano indaga su una serie di misteriosi omicidi in un'abbazia medievale.",
                'price' => 19.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Orgoglio e Pregiudizio',
                'publication_year' => 1813,
                'plot' => "Elizabeth Bennet affronta i pregiudizi sociali e sentimentali dell'Inghilterra ottocentesca.",
                'price' => 13.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Conte di Montecristo',
                'publication_year' => 1844,
                'plot' => 'Un uomo ingiustamente imprigionato pianifica una lunga vendetta.',
                'price' => 21.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Fahrenheit 451',
                'publication_year' => 1953,
                'plot' => 'In un futuro distopico i libri vengono bruciati per impedire il libero pensiero.',
                'price' => 15.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Dracula',
                'publication_year' => 1897,
                'plot' => 'Un giovane avvocato incontra il leggendario conte vampiro in Transilvania.',
                'price' => 16.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Frankenstein',
                'publication_year' => 1818,
                'plot' => 'Uno scienziato crea una creatura che finirà per perseguitarlo.',
                'price' => 15.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Lo Hobbit',
                'publication_year' => 1937,
                'plot' => 'Bilbo Baggins parte per un\'avventura alla ricerca di un tesoro custodito da un drago.',
                'price' => 17.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Piccolo Principe',
                'publication_year' => 1943,
                'plot' => 'Un bambino proveniente da un altro pianeta insegna il valore dell\'amicizia e dell\'amore.',
                'price' => 24.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Moby Dick',
                'publication_year' => 1851,
                'plot' => 'Il capitano Achab dà la caccia alla gigantesca balena bianca.',
                'price' => 18.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Shining',
                'publication_year' => 1977,
                'plot' => 'Una famiglia rimane isolata in un hotel infestato durante l\'inverno.',
                'price' => 20.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'It',
                'publication_year' => 1986,
                'plot' => 'Un gruppo di amici affronta un\'antica entità malvagia che assume la forma delle paure più profonde.',
                'price' => 26.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'La Strada',
                'publication_year' => 2006,
                'plot' => 'Padre e figlio attraversano un mondo devastato da un\'apocalisse.',
                'price' => 17.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Norwegian Wood',
                'publication_year'=> 1987,
                'plot' => 'Un giovane affronta il dolore, l\'amore e la crescita personale nella Tokyo degli anni Sessanta.',
                'price' => 18.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Codice Da Vinci',
                'publication_year' => 2003,
                'plot' => 'Un professore segue indizi nascosti in celebri opere d\'arte per svelare un antico segreto.',
                'price' => 16.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Angeli e Demoni',
                'publication_year' => 2000,
                'plot' => 'Robert Langdon cerca di fermare una minaccia contro il Vaticano.',
                'price' => 16.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Cacciatore di Aquiloni',
                'publication_year' => 2003,
                'plot' => 'Due amici crescono nell\'Afghanistan sconvolto dalla guerra.',
                'price' => 18.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Mille Splendidi Soli',
                'publication_year' => 2007,
                'plot' => 'Due donne intrecciano le proprie vite affrontando guerre e oppressione.',
                'price' => 18.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'La Ragazza del Treno',
                'publication_year' => 2015,
                'plot' => 'Una donna diventa testimone inconsapevole di un misterioso crimine.',
                'price' => 15.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Silenzio degli Innocenti',
                'publication_year' => 1988,
                'plot' => 'Una giovane agente dell\'FBI chiede aiuto a un serial killer per catturarne un altro.',
                'price' => 17.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Jurassic Park',
                'publication_year' => 1990,
                'plot' => 'Un parco popolato da dinosauri clonati si trasforma in un incubo.',
                'price' => 19.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Ready Player One',
                'publication_year' => 2011,
                'plot' => 'Un adolescente partecipa a una caccia al tesoro in un enorme mondo virtuale.',
                'price' => 18.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Neuromante',
                'publication_year' => 1984,
                'plot' => 'Un hacker viene coinvolto in una missione che cambierà il futuro dell\'intelligenza artificiale.',
                'price' => 17.50,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Foundation',
                'publication_year' => 1951,
                'plot' => 'Uno scienziato tenta di salvare la conoscenza umana dal collasso dell\'Impero Galattico.',
                'price' => 19.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Io, Robot',
                'publication_year' => 1950,
                'plot' => 'Una raccolta di racconti esplora il rapporto tra uomini e robot governati dalle Tre Leggi.',
                'price' => 16.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Il Richiamo della Foresta',
                'publication_year' => 1903,
                'plot' => 'Un cane domestico riscopre il proprio istinto selvaggio nei ghiacci del Nord.',
                'price' => 13.90,
                // 'author_id' => '',
                // 'editor_id' => '',
            ],
            [
                'title' => 'Le Cronache di Narnia: Il Leone, la Strega e l\'Armadio',
                'publication_year' => 1950,
                'plot' => 'Quattro fratelli scoprono un mondo magico minacciato da una potente strega.',
                'price' => 17.00,
                // 'author_id' => '',
                // 'editor_id' => '',
            ]
        ];
    }
}
